import { TransformConfig } from "../../types";

export const financialTransformConfig: TransformConfig = {
  fieldMap: {
    ticker: "symbol",
    yearReport: "year",
    lengthReport: "quarter",
    updateDate: "updatedAt",
    revenue: "revenue",
    revenueGrowth: "revenueGrowth",
    netProfit: "netProfit",
    netProfitGrowth: "netProfitGrowth",
    roe: "roe",
    roic: "roic",
    roa: "roa",
    pe: "pe",
    pb: "pb",
    eps: "eps",
    epsTTM: "epsTTM",
    currentRatio: "currentRatio",
    cashRatio: "cashRatio",
    quickRatio: "quickRatio",
    de: "debtToEquity",
    le: "longTermDebtToEquity",
    ebitda: "ebitda",
    ebit: "ebit",
    netProfitMargin: "netProfitMargin",
    grossMargin: "grossMargin",
    ev: "enterpriseValue",
    issueShare: "issuedShares",
    ps: "ps",
    pcf: "pcf",
    bvps: "bookValuePerShare",
    evPerEbitda: "evToEbitda",
    dividend: "dividend",
    charterCapital: "charterCapital",
  },
  priceFields: [],
  dateFields: ["updatedAt"],
  percentFields: ["roe", "roic", "roa", "revenueGrowth", "netProfitGrowth", "netProfitMargin", "grossMargin"],
  keepExtra: true,
};
