export const TRADING_URL = "https://apipubaws.tcbs.com.vn/stock-insight/v1/stock/second-tc-price";

export const priceBoardMapping = {
  t: "Mã CP",
  cp: "Giá",
  fv: "KLBD/TB5D",
  mav: "T.độ GD",
  nstv: "KLGD ròng(CM)",
  nstp: "%KLGD ròng (CM)",
  rsi: "RSI",
  macdv: "MACD Hist",
  macdsignal: "MACD Signal",
  tsignal: "Tín hiệu KT",
  avgsignal: "Tín hiệu TB động",
  ma20: "MA20",
  ma50: "MA50",
  ma100: "MA100",
  session: "Phiên +/- ",
  mscore: "Đ.góp VNINDEX",
  pe: "P/E",
  pb: "P/B",
  roe: "ROE",
  oscore: "TCRating",
  ev: "TCBS định giá",
  mw3d: "% thay đổi giá 3D",
  mw1m: "% thay đổi giá 1M",
  mw3m: "% thay đổi giá 3M",
  mw1y: "% thay đổi giá 1Y",
  rs3d: "RS 3D",
  rs1m: "RS 1M",
  rs3m: "RS 3M",
  rs1y: "RS 1Y",
  rsavg: "RS TB",
  hp1m: "Đỉnh 1M",
  hp3m: "Đỉnh 3M",
  hp1y: "Đỉnh 1Y",
  lp1m: "Đáy 1M",
  lp3m: "Đáy 3M",
  lp1y: "Đáy 1Y",
  hp1yp: "%Đỉnh 1Y",
  lp1yp: "%Đáy 1Y",
  delta1m: "%Giá - %VNI (1M)",
  delta1y: "%Giá - %VNI (1Y)",
  bv: "Khối lượng Dư mua",
  av: "Khối lượng Dư bán",
  hmp: "Khớp nhiều nhất",
  vnipe: "VNINDEX P/E",
  vnipb: "VNINDEX P/B",
};
