export const BASE_URL = "https://trading.vietcap.com.vn";
export const CHART_URL = BASE_URL + "/api/chart/OHLCChart/gap";
export const ALL_SYMBOLS_URL = "https://ai.vietcap.com.vn/api/get_all_tickers";
export const GRAPHQL_URL = BASE_URL + "/data-mt/graphql";

export const INTERVAL_MAP = {
  "1m": "ONE_MINUTE",
  "5m": "ONE_MINUTE",
  "15m": "ONE_MINUTE",
  "30m": "ONE_MINUTE",
  "1H": "ONE_HOUR",
  "1D": "ONE_DAY",
  "1W": "ONE_DAY",
  "1M": "ONE_DAY",
};

export const GROUP_CODE = [
  "HOSE",
  "VN30",
  "VNMidCap",
  "VNSmallCap",
  "VNAllShare",
  "VN100",
  "ETF",
  "HNX",
  "HNX30",
  "HNXCon",
  "HNXFin",
  "HNXLCap",
  "HNXMSCap",
  "HNXMan",
  "UPCOM",
  "FU_INDEX",
  "FU_BOND",
  "BOND",
  "CW",
];

export const PERIOD_MAP = { year: "Y", quarter: "Q" };
export const SUPPORTED_LANGUAGES = ["vi", "en"];

export const REPORT_MAP = { ticker: "CP", yearReport: "Năm", lengthReport: "Kỳ" };
export const UNIT_MAP = { BILLION: "tỷ", PERCENT: "%", INDEX: "index", MILLION: "triệu" };
export const REPORT_NAME = ["Chỉ tiêu cân đối kế toán", "Chỉ tiêu lưu chuyển tiền tệ", "Chỉ tiêu kết quả kinh doanh"];
export const ICB4_COMTYPE_CODE_MAP = {
  "Bán lẻ phức hợp": "CT",
  "Bảo hiểm nhân thọ": "BH",
  "Bảo hiểm phi nhân thọ": "BH",
  "Bất động sản": "CT",
  "Chuyển phát nhanh": "CT",
  "Chăm sóc y tế": "CT",
  "Chất thải & Môi trường": "CT",
  "Containers & Đóng gói": "CT",
  "Công nghiệp phức hợp": "CT",
  "Công nghệ sinh học": "CT",
  "Dược phẩm": "CT",
  "Dịch vụ Máy tính": "CT",
  "Dịch vụ giải trí": "CT",
  "Dịch vụ tiêu dùng chuyên ngành": "CT",
  "Dịch vụ truyền thông": "CT",
  "Dịch vụ vận tải": "CT",
  "Dụng cụ y tế": "CT",
  "Giải trí & Truyền thông": "CT",
  "Giầy dép": "CT",
  "Hàng May mặc": "CT",
  "Hàng cá nhân": "CT",
  "Hàng không": "CT",
  "Hàng điện & điện tử": "CT",
  Internet: "CT",
  "Khai khoáng": "CT",
  "Khai thác Than": "CT",
  "Khai thác vàng": "CT",
  "Kho bãi, hậu cần và bảo dưỡng": "CT",
  "Khách sạn": "CT",
  "Kim Loại màu": "CT",
  "Lâm sản và Chế biến gỗ": "CT",
  "Lốp xe": "CT",
  "Máy công nghiệp": "CT",
  "Môi giới chứng khoán": "CK",
  "Ngân hàng": "NH",
  "Nhà cung cấp thiết bị": "CT",
  "Nhà hàng và quán bar": "CT",
  Nhôm: "CT",
  "Nhựa, cao su & sợi": "CT",
  "Nuôi trồng nông & hải sản": "CT",
  Nước: "CT",
  "Phân phối dược phẩm": "CT",
  "Phân phối hàng chuyên dụng": "CT",
  "Phân phối thực phẩm": "CT",
  "Phân phối xăng dầu & khí đốt": "CT",
  "Phần cứng": "CT",
  "Phần mềm": "CT",
  "Phụ tùng ô tô": "CT",
  "Quản lý tài sản": "NH",
  "Sách, ấn bản & sản phẩm văn hóa": "CT",
  "Sản phẩm hóa dầu, Nông dược & Hóa chất khác": "CT",
  "Sản xuất & Phân phối Điện": "CT",
  "Sản xuất bia": "CT",
  "Sản xuất giấy": "CT",
  "Sản xuất và Khai thác dầu khí": "CT",
  "Sản xuất ô tô": "CT",
  "Thiết bị gia dụng": "CT",
  "Thiết bị viễn thông": "CT",
  "Thiết bị và Dịch vụ Dầu khí": "CT",
  "Thiết bị văn phòng": "CT",
  "Thiết bị y tế": "CT",
  "Thiết bị điện": "CT",
  "Thuốc lá": "CT",
  "Thép và sản phẩm thép": "CT",
  "Thực phẩm": "CT",
  "Tiện ích khác": "CT",
  "Tài chính cá nhân": "NH",
  "Tài chính đặc biệt": "CT",
  "Tái bảo hiểm": "BH",
  "Tư Vấn, Định giá, Môi giới Bất động sản": "CT",
  "Tư vấn & Hỗ trợ KD": "CT",
  "Vang & Rượu mạnh": "CT",
  "Viễn thông cố định": "CT",
  "Viễn thông di động": "CT",
  "Vận tải Thủy": "CT",
  "Vận tải hành khách & Du lịch": "CT",
  "Vật liệu xây dựng & Nội thất": "CT",
  "Xe tải & Đóng tàu": "CT",
  "Xây dựng": "CT",
  "Điện tử tiêu dùng": "CT",
  "Đào tạo & Việc làm": "CT",
  "Đường sắt": "CT",
  "Đồ chơi": "CT",
  "Đồ gia dụng lâu bền": "CT",
  "Đồ gia dụng một lần": "CT",
  "Đồ uống & giải khát": "CT",
};

export const INDEX_SYMBOLS = ["VNINDEX", "VN30", "VN100", "HNXIndex", "HNX30", "HNXUpcomIndex"];
