export interface TickerFinancialRatio {
  yearReport: number;
  lengthReport: number;
  updateDate: number;
  revenue: number;
  revenueGrowth: number;
  netProfit: number;
  netProfitGrowth: number;
  ebitMargin: number;
  roe: number;
  roic: number;
  roa: number;
  pe: number;
  pb: number;
  eps: number;
  currentRatio: number;
  cashRatio: number;
  quickRatio: number;
  interestCoverage: number;
  ae: number;
  fae: number;
  netProfitMargin: number;
  grossMargin: number;
  ev: number;
  issueShare: number;
  ps: number;
  pcf: number;
  bvps: number;
  evPerEbitda: number;
  at: number;
  fat: number;
  acp: number | null;
  dso: number;
  dpo: number;
  epsTTM: number;
  charterCapital: number;
  RTQ4: number;
  charterCapitalRatio: number;
  RTQ10: number;
  dividend: number;
  ebitda: number;
  ebit: number;
  le: number;
  de: number;
  ccc: number | null;
  RTQ17: number;
}
